### ISSUE TITLE
Realtime Capabilities

### ISSUE THREAD

**Issue by jacob-israel-turner** [CarbonLDP/carbonldp#9]
Having (briefly) run through the JavaScript SDK "getting started", I don't see any references to realtime capabilities/sockets.  Have I missed anything?

I've used Firebase extensively in the past.  I'm really excited by the ideas around carbonldp.  The free realtime capabilities that come with Firebase are extremely valuable to me as a consumer.  I would be more inclined to explore carbonldp further if it had similar functionality.

**Comment by MiguelAraCo** [comment]
Hello Jacob, thanks for checking out CarbonLDP!

Unfortunately the platform doesn't currently have realtime capabilities/sockets. We are currently designing its implementation as we also see it as an extremely valuable feature.

While designing new functionality for CarbonLDP we try to avoid creating any proprietary design and instead we always try to find standards/specifications to follow to provide better interoperability. As I understand Firebase uses a combination of WebSockets/SSE and a fallback of long polling to accomplish realtime notifications. We are also considering HTTP/2 server push but it is not yet well supported by most platforms/browsers.

Are you inclined towards one technology in particular?

**Comment by jacob-israel-turner** [comment]
I'm not necessarily particular to any tech.  If you provide an open push API, I would be more inclined to consume WebSockets.  But most of my use will be through the JavaScript SDK.  As long as there is widespread browser support/graceful fallback, I'd be a happy camper!

If you need testing/implementing in the SDK, feel free to reach out to me.  I'd be more than happy to help.

**Comment by MiguelAraCo** [comment]
We are about to implement real-time capabilities to CarbonLDP. The current design is the following:

## Platform changes

- The platform will use **WebSockets** with fallback support using **SockJS** to notify clients of data changing events
- **STOMP** will be used as the protocol on top of WS/SockJS
- The platform will use as a broker relay any configured **AMQP** implementations
- By using AMQP, the STOMP address will have the form:

  ```
  /topic/{event-target}.{event-type}.{document-path-1}.{document.path-2}.{document-path-n}
  ```

  Example:
  `d.m.projects.project-alpha.members.john` would mean: notify me when the document document `projects/project-alpha/members/john/` is modified

- The initially supported event types and targets are:

  - Child created `c.c`
  - AccessPoint created `a.c`
  - Document modified `d.m`
  - Document deleted `d.d`
  - Member added `m.a`
  - Member removed `m.d`

- Due to the use of AMQP, addresses will support the following wildcards:
  
  - `#` to indicate anything on lower levels (e.g. `c.c.#` means "any child created on the platform")
  - `*` to indicate anything on that specific level (e.g. `c.c.projects.*` means "any child created under the `projects/` document"

- Wildcards will be accepted in any path piece (e.g. `*.c.#` means any creation)
- Wildcards are not accepted as part of path pieces (e.g. `c.c.project-*` is invalid)
- Events will carry payload that will look like the following example:

  ```
  {
    "@id": "_b1",
    "@type": [ "c:MemberAddedEvent" ],
    "c:target": "https://my-carbon-instance.com/affected-document/",
    "c:details": {
      "@type": "c:MemberAddedEventDetails",
      "c:member": "https://my-carbon-instance.com/new-member/"
    }
  }
  ```

  Event details are still to be defined.

## JS SDK changes

- The JS SDK will accept **Ant** style patterns instead, making the following convertions:

  - `**` === `#`
  - `*` === `*`

- The following methods will be added:

  - `documents.on( eventType, uriPattern, callback )`
  - `documents.off( eventType, uriPattern, callback )`
  - `documents.one( eventType, uriPattern, callback )`

  - `documents.onCreation vs onCreated vs onDocumentCreated`
  - `documents.onChildCreated( uriPattern, callback )`
  - `documents.onAccessPointCreated( uriPattern, callback )`
  - `documents.onDocumentModified( uriPattern, callback )`
  - `documents.onDocumentDeleted( uriPattern, callback )`
  - `documents.onMemberAdded( uriPattern, callback )`
  - `documents.onMemberRemoved( uriPattern, callback )`

  - `persistedDocument.onChildCreated( callback )`
  - `persistedDocument.onAccessPointCreated( callback )`
  - `persistedDocument.onDocumentModified( callback )`
  - `persistedDocument.onDocumentDeleted( callback )`
  - `persistedDocument.onMemberAdded( callback )`
  - `persistedDocument.onMemberRemoved( callback )`

## TODOs

- Document URI escaping mechanisms (e.g., what happens if the URI contains a `.` character)

**Comment by jacob-israel-turner** [comment]
This looks awesome! When will this be available for testing?

**Comment by MiguelAraCo** [comment]
We plan to release a new version with this feature in two weeks

**Comment by MiguelAraCo** [comment]
After some testing we concluded that there are no restrictions on the AMQP path's length. So the events aren't going to be abbreviations, instead they will be the following ones:

| Event | Starting key |
| --- | --- |
| Child created | `child.created` |
| AccessPoint created | `access-point.created` |
| Document modified | `document.modified` |
| Document deleted | `document.deleted` |
| Member added | `member.added` |
| Member removed | `member.removed` |

**Comment by MiguelAraCo** [comment]
The URIs of the documents being affected are going to be converted to AMQP paths using the following algorithm:
- Remove the host URL from the URI to get just the relative document path (e.g. document-1/document2/)
- Replace `.` characters for `^` (`.` are reserved characters in AMQP paths)
- Remove ending `/` character (if there is one)
- Replace `/` characters with `.`
- Encode the document path
- Forge the AMQP path starting with: `"/topic/" + targetType + "." + eventType`
- If the document path isn't empty (like when the root document is the affected one), add the following: `amqpPath = amqpPath + "." + uriPath`
- If it is empty don't add the document path to the AMQP path
